### PR TITLE
Replace `http s ://` with `https://`

### LINKED ISSUE #15: All instances of `https` are currently output as `http s `
It seems like there's something weird going on with `https` URLs in the `licenseText` fields &ndash; they all have a space on either side of the `s` (i.e. `http s ://`).

### PR DESCRIPTION
**Pull request by TiagoDanin**
Fixes #15

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you also try to fix the source?

**Comment by TiagoDanin** [comment]
@sindresorhus in https://github.com/spdx ? or update files (spdx-full.json, spdx-simple.json, spdx.json...) ?

**Comment by sindresorhus** [comment]
In https://github.com/spdx

**Comment by TiagoDanin** [comment]
LicenseListPublisher is in Java and i haven't studied Java. 
Issue in LicenseListPublisher: https://github.com/spdx/LicenseListPublisher/issues/42

**Pull request merged**
